package com.stocksense.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    TOKEN_REFRESHED,
    PREDICTION_REQUESTED,
    WATCHLIST_ADDED,
    WATCHLIST_REMOVED,
    BACKTEST_REQUESTED,
    ADMIN_VIEWED_METRICS,
    ADMIN_VIEWED_AUDIT_LOGS,
    MODEL_TRAINED
}
